item {
    name: "meeting_room"
    id: 1
    display_name: "meeting_room"
}
item {
    name: "office_room1"
    id: 2
    display_name: "office_room1"
}
item {
    name: "office_room2"
    id: 3
    display_name: "office_room2"
}